version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node
    depends_on:
      - mongo
    ports:
      - ${APP_PORT-3000}:${APP_PORT-3000}
    volumes:
      - ./node-app:/node-app
      - ./env:/node-app/.env
    networks:
      - my-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT-27017}:${MONGO_PORT-27017}
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - my-network

networks:
  my-network:
      driver: bridge